"""initial schema

Revision ID: 73f7c0e3b3b8
Revises: 
Create Date: 2026-09-15 20:13:03.354605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('textbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('llm_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_code', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=1), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_code')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('image_discarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_return', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('llm_job_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 3', name='ck_problem_difficulty'),
    sa.ForeignKeyConstraint(['format_id'], ['format.id'], ),
    sa.ForeignKeyConstraint(['llm_job_id'], ['llm_job.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_scope',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'unit_id')
    )
    op.create_table('test_trend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('llm_job_id', sa.Integer(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 3', name='ck_test_trend_difficulty'),
    sa.ForeignKeyConstraint(['format_id'], ['format.id'], ),
    sa.ForeignKeyConstraint(['llm_job_id'], ['llm_job.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_prerequisite',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_unit_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('llm_job_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['llm_job_id'], ['llm_job.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('unit_id', 'prerequisite_unit_id')
    )
    op.create_table('worksheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=1), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('llm_job_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['llm_job_id'], ['llm_job.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.CheckConstraint('step BETWEEN 1 AND 3', name='ck_hint_step'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'step', name='uq_hint_problem_step')
    )
    op.create_table('problem_prerequisite',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'unit_id')
    )
    op.create_table('worksheet_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('is_return', sa.Boolean(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_item_id'], ['worksheet_item.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worksheet_id', 'item_no', name='uq_worksheet_item_no')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_sheet_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_item_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('hint_step', sa.Integer(), nullable=False),
    sa.Column('went_return', sa.Boolean(), nullable=False),
    sa.Column('red_card', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.CheckConstraint('hint_step BETWEEN 0 AND 3', name='ck_attempt_hint_step'),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheet.id'], ),
    sa.ForeignKeyConstraint(['worksheet_item_id'], ['worksheet_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_sheet_id', 'worksheet_item_id', name='uq_attempt_sheet_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt')
    op.drop_table('worksheet_item')
    op.drop_table('problem_prerequisite')
    op.drop_table('hint')
    op.drop_table('answer_sheet')
    op.drop_table('worksheet')
    op.drop_table('unit_prerequisite')
    op.drop_table('test_trend')
    op.drop_table('test_scope')
    op.drop_table('problem')
    op.drop_table('lesson')
    op.drop_table('unit')
    op.drop_table('test')
    op.drop_table('student')
    op.drop_table('llm_job')
    op.drop_table('user')
    op.drop_table('textbook')
    op.drop_table('school')
    op.drop_table('format')
    # ### end Alembic commands ###
